package com.axiomasoluciones.accidentinvestigation.models.entity.util.persistencia;

public enum IncidentType {
    ATRAPADO_POR,
    CAIDA_DISTINTO_NIVEL,
    CAIDA_MISMO_NIVEL,
    CONTACTO_CALOR,
    CONTACTO_ELECTRICIDAD,
    CONTACTO_QUIMICOS,
    CONTACTO_FRIO,
    CONTACTO_ELEMENTO_CORTANTE,
    CONTACTO_ELEMENTO_PUNZANTE,
    EXPOSICION_GASES,
    EXPOSICION_RADIACTIVIDAD,
    GOLPEADO_CONTRA,
    GOLPEADO_POR,
    PROYECCION_FLUIDOS,
    PROYECCION_PARTICULAS;
}
