package com.axiomasoluciones.accidentinvestigation.models.entity.util;

public enum IncidentType {
    GOLPEADO_POR,
    GOLPEADO_CONTRA,
    ATRAPADO_ENTRE,
    ATRAPADO_POR,
    PROYECCION_FUIDOS,
    CAIDA_MISMO_NIVEL,
    CAIDA_DISTINTO_NIVEL,
    CONTACTO_QUIMICOS,
    CONTACTO_ELECTRICIDAD,
    CONTACTO_CALOR,
    CONTACTO_FRIO,
    CONTACTO_CORTANTE,
    CONTACTO_PUNZANTE,
    EXPOSICION_RADIACION,
    EXPOSICION_GASES,
    EXPOSICON_PARTICULAS

}
