package com.axiomasoluciones.accidentinvestigation.models.entity.util;

public enum MentalTension {
    SOBRECARGA_EMOCIONAL,
    FATIGA_EMOCIONAL,
    DEMANDAS_EXTREMADAS_DE_OPSION,
    RUTINA_MONOTA,
    DEMANDAS_EXTREMADAS_CONCENTRACION,
    ACTIVIDAD_SINSENTIDO,
    DEMANDAS_CONFUSAS,
    PETICIONES_CONFLICTIVAS,
    PREOCUPACION_PROBLEMAS,
    ENFEMEDAD_MENTAL

    }
