package com.axiomasoluciones.accidentinvestigation.models.entity.util;

public enum PhysicalTension {

    LESION_ENFERMEDAD,
    FATIGA_CARGA,
    FATIGA_DURACIÓN_TAREAS,
    FATIGA_DESCANSO,
    FATIGA_SOBRECARGA_SENSITIVA,
    EXPOSICION_TEMPERATURAS_EXTREMAS,
    INSUFICIENTE_OXIGENO,
    VARIACION_PRESION_ATMOSFERICA,
    MOVIMIENTO_RESTRINGIDOS,
    INSUFICIENTE_AZUCAR_SANGRE,
    DROGRAS


    }
